import { getConfigValue, getDefaultConfigValue } from './default-config.js';

const FEATURE_DEFINITIONS = [
  {
    id: 'model-routing',
    metricKey: 'model-routing',
    configKey: 'smartRouting',
    dashboardCategory: 'measured-savings',
    dashboardCategoryLabel: 'Measured savings',
    measurementLabel: 'נמדד בדשבורד',
    measurementTone: 'measured',
    icon: '🧠',
    title: 'ניתוב מודל חכם',
    type: 'auto',
    recommendationLabel: 'להשאיר פעיל',
    recommendationTone: 'recommended',
    desc: 'מעביר משימות פשוטות ל-Haiku ומשימות כבדות ל-Opus. זה חיסכון בעלות בלי לקצר את תוכן הבקשה עצמה.',
  },
  {
    id: 'trim-log',
    metricKey: 'trim-log',
    configKey: 'trimLogs',
    dashboardCategory: 'measured-savings',
    dashboardCategoryLabel: 'Measured savings',
    measurementLabel: 'נמדד בדשבורד',
    measurementTone: 'measured',
    icon: '✂️',
    title: 'קיצוץ לוגים ארוכים',
    type: 'auto',
    recommendationLabel: 'להשאיר פעיל, אבל לבדוק כשזה קריטי',
    recommendationTone: 'caution',
    desc: 'מזהה paste של לוג ארוך, מנסה לחלץ שורות שגיאה ו-stack trace רלוונטיים, ושומר גם tail קצר. עדיין lossy, אבל יותר שקוף ובטוח מ-"רק 50 השורות האחרונות".',
  },
  {
    id: 'translate',
    metricKey: 'translate',
    configKey: 'translate',
    dashboardCategory: 'measured-savings',
    dashboardCategoryLabel: 'Measured savings',
    measurementLabel: 'נמדד רק אם הופעל',
    measurementTone: 'measured',
    icon: '🌐',
    title: 'תרגום עברית → אנגלית',
    type: 'auto',
    recommendationLabel: 'כבוי כברירת מחדל',
    recommendationTone: 'optional',
    desc: 'זמין כאופציה, אבל כבוי כברירת מחדל כי תרגום יכול לשנות ניסוח, ניואנס ואפילו כוונה.',
  },
  {
    id: 'politeness',
    metricKey: 'politeness',
    configKey: 'stripPoliteness',
    dashboardCategory: 'measured-savings',
    dashboardCategoryLabel: 'Measured savings',
    measurementLabel: 'נמדד בדשבורד',
    measurementTone: 'measured',
    icon: '🧹',
    title: 'ניקוי נימוסים',
    type: 'auto',
    recommendationLabel: 'להשאיר פעיל',
    recommendationTone: 'recommended',
    desc: 'מסיר מילים כמו "בבקשה" ו-"תודה" בלי לשנות את מהות הבקשה. זה אחד החיסכונות הבטוחים יותר.',
  },
  {
    id: 'resolve-paths',
    configKey: 'resolvePaths',
    dashboardCategory: 'workflow-quality',
    dashboardCategoryLabel: 'Workflow / quality',
    measurementLabel: 'דיוק workflow, לא חיסכון ישיר',
    measurementTone: 'advice',
    icon: '📁',
    title: 'הרחבת נתיבים',
    type: 'auto',
    recommendationLabel: 'להשאיר פעיל',
    recommendationTone: 'recommended',
    desc: 'מחליף שמות קבצים לנתיבים מוחלטים כדי לצמצם הלוך-חזור עם המודל. זה בעיקר פיצ\'ר דיוק, לא פיצ\'ר חיסכון.',
  },
  {
    id: 'code-compress',
    metricKey: 'code-compress',
    configKey: 'codeCompression',
    dashboardCategory: 'measured-savings',
    dashboardCategoryLabel: 'Measured savings',
    measurementLabel: 'נמדד רק אם הופעל',
    measurementTone: 'measured',
    icon: '📦',
    title: 'כיווץ קוד',
    type: 'auto',
    recommendationLabel: 'כבוי כברירת מחדל',
    recommendationTone: 'optional',
    desc: 'מסיר comments ושורות debug מתוך code blocks. זה יכול לחסוך טוקנים, אבל גם למחוק רמזים שדווקא חשובים לדיבוג.',
  },
  {
    id: 'truncate',
    metricKey: 'truncate',
    configKey: 'truncateLargePastes',
    dashboardCategory: 'measured-savings',
    dashboardCategoryLabel: 'Measured savings',
    measurementLabel: 'נמדד רק אם הופעל',
    measurementTone: 'measured',
    icon: '📄',
    title: 'חיתוך קבצים גדולים',
    type: 'auto',
    recommendationLabel: 'כבוי כברירת מחדל',
    recommendationTone: 'optional',
    desc: 'שומר רק חלק מהשורות בקלט גדול במיוחד. זה feature lossy ולכן נשאר זמין אבל לא דלוק אוטומטית.',
  },
  {
    id: 'dedupe',
    metricKey: 'dedupe',
    configKey: 'dedupeLongInput',
    dashboardCategory: 'measured-savings',
    dashboardCategoryLabel: 'Measured savings',
    measurementLabel: 'נמדד רק אם הופעל',
    measurementTone: 'measured',
    icon: '🔁',
    title: 'הסרת תוכן כפול',
    type: 'auto',
    recommendationLabel: 'כבוי כברירת מחדל',
    recommendationTone: 'optional',
    desc: 'מסיר שורות זהות מקלט ארוך. לפעמים זה עוזר, אבל לפעמים דווקא החזרה עצמה חשובה, לכן זה opt-in.',
  },
  {
    id: 'output-hint',
    metricKey: 'output-hint',
    configKey: 'responseLengthHints',
    dashboardCategory: 'measured-savings',
    dashboardCategoryLabel: 'Measured savings',
    measurementLabel: 'נמדד רק אם הופעל',
    measurementTone: 'measured',
    icon: '📏',
    title: 'הגבלת אורך תגובה',
    type: 'auto',
    recommendationLabel: 'כבוי כברירת מחדל',
    recommendationTone: 'optional',
    desc: 'מוסיף בקשות קיצור לתשובות קצרות מאוד. זה חוסך output tokens, אבל עלול לקצר תשובה יותר מדי.',
  },
  {
    id: 'secret-scanner',
    configKey: 'secretScanner',
    dashboardCategory: 'workflow-quality',
    dashboardCategoryLabel: 'Workflow / quality',
    measurementLabel: 'בטיחות, לא חיסכון',
    measurementTone: 'advice',
    icon: '🔑',
    title: 'סורק סודות',
    type: 'auto',
    recommendationLabel: 'להשאיר פעיל',
    recommendationTone: 'recommended',
    desc: 'מחפש API keys, סיסמאות וטוקנים לפני שליחה. זה פיצ\'ר בטיחות, לא פיצ\'ר חיסכון.',
  },
  {
    id: 'git-context',
    configKey: 'gitContext',
    dashboardCategory: 'workflow-quality',
    dashboardCategoryLabel: 'Workflow / quality',
    measurementLabel: 'איכות, לא חיסכון ישיר',
    measurementTone: 'advice',
    icon: '🌿',
    title: 'Git Context אוטומטי',
    type: 'auto',
    recommendationLabel: 'להשאיר פעיל',
    recommendationTone: 'recommended',
    desc: 'מוסיף git status / diff כשנראה שיש באג או שינוי קוד. זה אפילו מגדיל prompt לפעמים, אבל משפר איכות.',
  },
  {
    id: 'cache',
    metricKey: 'cache',
    configKey: 'promptCache',
    dashboardCategory: 'measured-savings',
    dashboardCategoryLabel: 'Measured savings',
    measurementLabel: 'נמדד בדשבורד',
    measurementTone: 'measured',
    icon: '💾',
    title: 'מטמון תגובות',
    type: 'auto',
    recommendationLabel: 'להשאיר פעיל',
    recommendationTone: 'recommended',
    desc: 'כשאותו prompt נשלח שוב עם אותו model, CCSO מחזיר תשובה שמורה וחוסך בקשה מלאה. יש גם נרמול שמרני של whitespace כדי לתפוס חזרות אמיתיות בלי לשנות משמעות.',
  },
  {
    id: 'handoff',
    dashboardCategory: 'quota-hygiene',
    dashboardCategoryLabel: 'Quota / session hygiene',
    measurementLabel: 'היגיינת סשן, לא חיסכון ישיר',
    measurementTone: 'quota',
    icon: '🔄',
    title: 'Handoff אוטומטי',
    type: 'auto',
    recommendationLabel: 'להשאיר פעיל',
    recommendationTone: 'recommended',
    desc: 'כשהעלות, הזמן או מספר הפקודות חוצים סף, CCSO שומר handoff כדי למנוע סשנים מנופחים מדי.',
  },
  {
    id: 'time-guard',
    configKey: 'timeGuard',
    dashboardCategory: 'quota-hygiene',
    dashboardCategoryLabel: 'Quota / session hygiene',
    measurementLabel: 'התרעת session hygiene',
    measurementTone: 'quota',
    icon: '⏰',
    title: 'TimeGuard',
    type: 'auto',
    recommendationLabel: 'להשאיר פעיל',
    recommendationTone: 'recommended',
    desc: 'מתריע כשסשן נמשך יותר מדי זמן. זה לא חוסך טוקנים ישירות, אבל מונע המשך עבודה במצב עייף/מבולגן.',
  },
  {
    id: 'memory',
    configKey: 'memoryEnabled',
    dashboardCategory: 'estimated-impact',
    dashboardCategoryLabel: 'Estimated context reuse',
    measurementLabel: 'משפר הקשר, לא נספר ישירות',
    measurementTone: 'estimated',
    icon: '🧩',
    title: 'זיכרון חוצה-סשן',
    type: 'manual',
    recommendationLabel: 'להשאיר פעיל לפי צורך',
    recommendationTone: 'manual',
    desc: 'שומר עובדות על הפרויקט ומזריק רק את העובדות הרלוונטיות ביותר תחת תקציב טוקנים. זה שומר הקשר בלי לנפח כל פרומפט מחדש.',
  },
  {
    id: 'briefs',
    configKey: 'briefsEnabled',
    dashboardCategory: 'estimated-impact',
    dashboardCategoryLabel: 'Estimated context reuse',
    measurementLabel: 'Brief reuse, לא נספר ישירות',
    measurementTone: 'estimated',
    icon: '📚',
    title: 'Reusable File Briefs',
    type: 'manual',
    recommendationLabel: 'להפעיל לקבצים שחוזרים הרבה',
    recommendationTone: 'manual',
    desc: 'שומר brief קצר לקובץ או מסמך ומזריק אותו רק כשהקובץ מוזכר שוב. זה עוזר להימנע מהדבקה חוזרת של אותו קונטקסט, אבל לא נספר כחיסכון קשיח כי CCSO לא יודע מה היית מדביק אחרת.',
  },
  {
    id: 'session-reset-advisor',
    configKey: 'resetAdvisor',
    dashboardCategory: 'quota-hygiene',
    dashboardCategoryLabel: 'Quota / session hygiene',
    measurementLabel: 'עצת reset, לא חיסכון ישיר',
    measurementTone: 'quota',
    icon: '🧭',
    title: 'Session Reset Advisor',
    type: 'auto',
    recommendationLabel: 'להשאיר פעיל',
    recommendationTone: 'recommended',
    desc: 'ממליץ על handoff או reset כשהסשן מתחיל להתנפח לפי מספר turns, זמן וטוקנים. זה שומר על הקשר נקי יותר, אבל לא נספר כחיסכון ישיר.',
  },
  {
    id: 'prompt-bundler',
    dashboardCategory: 'workflow-quality',
    dashboardCategoryLabel: 'Workflow / quality',
    measurementLabel: 'כלי workflow ידני',
    measurementTone: 'advice',
    icon: '📦',
    title: 'Prompt Bundler',
    type: 'manual',
    recommendationLabel: 'מומלץ כשיש כמה סעיפים יחד',
    recommendationTone: 'manual',
    desc: 'הפקודה `/bundle` מאגדת כמה שאלות או משימות לבקשה אחת מסודרת, כדי לטעון הקשר משותף פעם אחת בלבד ולהפחית הלוך-חזור.',
  },
  {
    id: 'prompt-history',
    configKey: 'promptHistory',
    dashboardCategory: 'workflow-quality',
    dashboardCategoryLabel: 'Workflow / quality',
    measurementLabel: 'כלי workflow מקומי',
    measurementTone: 'advice',
    icon: '📜',
    title: 'היסטוריית פרומפטים',
    type: 'manual',
    recommendationLabel: 'להשאיר פעיל לפי צורך',
    recommendationTone: 'manual',
    desc: 'שומר היסטוריה מקומית של הפרומפטים כדי שתוכל לחפש ולחזור על ניסוחים שעבדו.',
  },
  {
    id: 'templates',
    dashboardCategory: 'workflow-quality',
    dashboardCategoryLabel: 'Workflow / quality',
    measurementLabel: 'כלי workflow ידני',
    measurementTone: 'advice',
    icon: '📝',
    title: 'תבניות מוכנות',
    type: 'manual',
    recommendationLabel: 'זמין תמיד',
    recommendationTone: 'manual',
    desc: 'תבניות מוכנות ל-bug reports, code review, refactor, tests, docs ואבטחה.',
  },
  {
    id: 'dashboard',
    dashboardCategory: 'workflow-quality',
    dashboardCategoryLabel: 'Workflow / quality',
    measurementLabel: 'שקיפות ותצפית, לא חיסכון ישיר',
    measurementTone: 'advice',
    icon: '🎛️',
    title: 'Dashboard בדפדפן',
    type: 'manual',
    recommendationLabel: 'זמין תמיד',
    recommendationTone: 'manual',
    desc: 'מציג spend, net savings, breakdown לפי פיצ\'ר, סטטוס פלטפורמות, ואת ההפרדה בין Measured savings, Estimated impact ו-Workflow advice.',
  },
];

export function getFeatureCatalog(config) {
  return FEATURE_DEFINITIONS.map((feature) => {
    const hasToggle = Boolean(feature.configKey);
    const enabled = hasToggle ? Boolean(getConfigValue(config, feature.configKey)) : true;
    const defaultEnabled = hasToggle ? Boolean(getDefaultConfigValue(feature.configKey)) : null;

    return {
      ...feature,
      enabled,
      defaultEnabled,
      measurable: Boolean(feature.metricKey),
      stateLabel: hasToggle ? (enabled ? 'פעיל' : 'כבוי') : (feature.type === 'manual' ? 'זמין' : 'תמיד פעיל'),
      typeLabel: feature.type === 'auto' ? 'אוטומטי' : 'ידני',
    };
  });
}

export function getFeatureStateMap(config) {
  return Object.fromEntries(
    getFeatureCatalog(config).map((feature) => [
      feature.id,
      {
        enabled: feature.enabled,
        defaultEnabled: feature.defaultEnabled,
        stateLabel: feature.stateLabel,
        recommendationLabel: feature.recommendationLabel,
        recommendationTone: feature.recommendationTone,
        type: feature.type,
      },
    ]),
  );
}
